on:
  push:
    branches:
      - staging
jobs:
  deploy_production:
    name: Deploy backend to staging server
    runs-on: ubuntu-latest
    env:
      CONFIG_FILE: config-staging.json
    steps:
      - name: Install required packages
        run: sudo apt-get install -y lftp
      - name: Checkout
        uses: actions/checkout@v2
      - name: Decrypt configuration
        run: ./server/deploy/decrypt-config.sh
        env:
          CONFIG_DECRYPT_PASSPHRASE: ${{ secrets.CONFIG_DECRYPT_PASSPHRASE }}
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Deploy
        working-directory: server
        run: ./deploy/deploy.sh
      - name: Check HTTP status code
        shell: bash
        run: |
          BACKEND_URL=$(jq -r '.BACKEND_URL' "./server/deploy/$CONFIG_FILE")
          RESPONSE_CODE=$(curl -sL -w "%{http_code}" -I "$BACKEND_URL/hello" -o /dev/null)
          echo "HTTP response code from $BACKEND_URL/hello: $RESPONSE_CODE"
          [ "$RESPONSE_CODE" == "200" ]
